name: Deploy to GitHub Pages
on:
  push:
    branches:
      - feature/fear-of-all-developers
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Версия node

      - name: Install dependencies
        run: npm install

      - name: Run the project
        run: npm run

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ../src
